Repository ftlorg/ftl, pull requests merged in 2020-10, with the labels that each got.

#19 Implement ftl::deque
  include/ftl/deque.hpp
  include/ftl/deque_container_const_iterator.hpp
  include/ftl/deque_container_iterator.hpp
  include/ftl/ftl.hpp
  tests/CMakeLists.txt
  tests/test_deque.cpp
Labels: enhancement

#22 Implement ftl::unordered_map
  include/ftl/ftl.hpp
  include/ftl/iterator_traits.hpp
  include/ftl/unordered_map.hpp
  include/ftl/unordered_map_container_const_iterator.hpp
  include/ftl/unordered_map_container_iterator.hpp
  tests/CMakeLists.txt
  tests/test_unordered_map.cpp
  tests/test_unordered_map_container_iterator.cpp
Labels: enhancement

#21 Implement ftl::set
  include/ftl/ftl.hpp
  include/ftl/iterator_traits.hpp
  include/ftl/set.hpp
  include/ftl/set_container_const_iterator.hpp
  include/ftl/set_container_iterator.hpp
  tests/CMakeLists.txt
  tests/test_set.cpp
  tests/test_set_container_iterator.cpp
Labels: enhancement

#23 Implement ftl::forward_list
  include/ftl/forward_list.hpp
  include/ftl/forward_list_container_const_iterator.hpp
  include/ftl/forward_list_container_iterator.hpp
  include/ftl/ftl.hpp
  include/ftl/iterator_traits.hpp
  include/ftl/list_container_const_iterator.hpp
  include/ftl/list_container_iterator.hpp
  tests/CMakeLists.txt
  tests/test_forward_list.cpp
  tests/test_forward_list_container_iterator.cpp
Labels: enhancement

#24 Implement any method
  include/ftl/iterator_interface.hpp
  tests/CMakeLists.txt
  tests/test_array_container_iterator.cpp
  tests/test_enumerate_iterator.cpp
  tests/test_filter_iterator.cpp
  tests/test_forward_list_container_iterator.cpp
  tests/test_inspect_iterator.cpp
  tests/test_list_container_iterator.cpp
  tests/test_map_container_iterator.cpp
  tests/test_map_iterator.cpp
  tests/test_set_container_iterator.cpp
  tests/test_take_iterator.cpp
  tests/test_unordered_map_container_iterator.cpp
  tests/test_vector_container_iterator.cpp
Labels: enhancement

#25 Implement min method
  include/ftl/array_container_const_iterator.hpp
  include/ftl/container_iterator_member_provider.hpp
  include/ftl/enumerate_iterator.hpp
  include/ftl/filter_iterator.hpp
  include/ftl/inspect_iterator.hpp
  include/ftl/iterator_interface.hpp
  include/ftl/iterator_member_provider.hpp
  include/ftl/iterator_traits.hpp
  include/ftl/map_iterator.hpp
  include/ftl/take_iterator.hpp
  tests/test_array_container_iterator.cpp
  tests/test_enumerate_iterator.cpp
  tests/test_filter_iterator.cpp
  tests/test_forward_list_container_iterator.cpp
  tests/test_inspect_iterator.cpp
  tests/test_list_container_iterator.cpp
  tests/test_map_iterator.cpp
  tests/test_set_container_iterator.cpp
  tests/test_take_iterator.cpp
  tests/test_vector_container_iterator.cpp
Labels: enhancement

#26 Implement max method
  include/ftl/iterator_interface.hpp
  tests/test_array_container_iterator.cpp
  tests/test_enumerate_iterator.cpp
  tests/test_filter_iterator.cpp
  tests/test_forward_list_container_iterator.cpp
  tests/test_inspect_iterator.cpp
  tests/test_list_container_iterator.cpp
  tests/test_map_iterator.cpp
  tests/test_set_container_iterator.cpp
  tests/test_take_iterator.cpp
  tests/test_vector_container_iterator.cpp
Labels: enhancement

#27 Implement partition method
  include/ftl/iterator_interface.hpp
  tests/test_array_container_iterator.cpp
  tests/test_enumerate_iterator.cpp
  tests/test_filter_iterator.cpp
  tests/test_forward_list_container_iterator.cpp
  tests/test_inspect_iterator.cpp
  tests/test_list_container_iterator.cpp
  tests/test_map_container_iterator.cpp
  tests/test_map_iterator.cpp
  tests/test_set_container_iterator.cpp
  tests/test_take_iterator.cpp
  tests/test_unordered_map_container_iterator.cpp
  tests/test_vector_container_iterator.cpp
Labels: do not merge yet, enhancement

#29 Implement find method
  include/ftl/iterator_interface.hpp
  tests/test_array_container_iterator.cpp
  tests/test_enumerate_iterator.cpp
  tests/test_filter_iterator.cpp
  tests/test_forward_list_container_iterator.cpp
  tests/test_list_container_iterator.cpp
  tests/test_map_container_iterator.cpp
  tests/test_map_iterator.cpp
  tests/test_set_container_iterator.cpp
  tests/test_take_iterator.cpp
  tests/test_unordered_map_container_iterator.cpp
  tests/test_vector_container_iterator.cpp
Labels: enhancement

#31 Implement sum method
  include/ftl/iterator_interface.hpp
  tests/test_array_container_iterator.cpp
  tests/test_filter_iterator.cpp
  tests/test_list_container_iterator.cpp
  tests/test_map_iterator.cpp
  tests/test_set_container_iterator.cpp
  tests/test_take_iterator.cpp
  tests/test_vector_container_iterator.cpp
Labels: enhancement

#32 Implement product method
  include/ftl/iterator_interface.hpp
  tests/test_array_container_iterator.cpp
  tests/test_filter_iterator.cpp
  tests/test_map_iterator.cpp
  tests/test_take_iterator.cpp
  tests/test_vector_container_iterator.cpp
Labels: enhancement

#33 Implement collect into
  include/ftl/array_container_const_iterator.hpp
  include/ftl/from_iterator_trait.hpp
  include/ftl/iterator_interface.hpp
  include/ftl/iterator_member_provider.hpp
  include/ftl/iterator_traits.hpp
  include/ftl/map.hpp
  include/ftl/set.hpp
  include/ftl/unordered_map.hpp
  tests/test_array_container_iterator.cpp
  tests/test_enumerate_iterator.cpp
  tests/test_filter_iterator.cpp
  tests/test_forward_list_container_iterator.cpp
  tests/test_inspect_iterator.cpp
  tests/test_list_container_iterator.cpp
  tests/test_map_container_iterator.cpp
  tests/test_unordered_map_container_iterator.cpp
  tests/test_vector_container_iterator.cpp
Labels: enhancement

#35 Implement fold method
  include/ftl/iterator_interface.hpp
  tests/test_array_container_iterator.cpp
  tests/test_enumerate_iterator.cpp
  tests/test_filter_iterator.cpp
  tests/test_forward_list_container_iterator.cpp
  tests/test_inspect_iterator.cpp
  tests/test_list_container_iterator.cpp
  tests/test_map_container_iterator.cpp
  tests/test_map_iterator.cpp
  tests/test_set_container_iterator.cpp
  tests/test_take_iterator.cpp
  tests/test_unordered_map_container_iterator.cpp
Labels: enhancement

#38 Implement for_each
  include/ftl/iterator_interface.hpp
  tests/test_array_container_iterator.cpp
  tests/test_enumerate_iterator.cpp
  tests/test_filter_iterator.cpp
  tests/test_forward_list_container_iterator.cpp
  tests/test_inspect_iterator.cpp
  tests/test_list_container_iterator.cpp
  tests/test_map_container_iterator.cpp
  tests/test_map_iterator.cpp
  tests/test_set_container_iterator.cpp
  tests/test_take_iterator.cpp
  tests/test_unordered_map_container_iterator.cpp
  tests/test_vector_container_iterator.cpp
Labels: enhancement

#39 Fix compilation issue on MSVC
  include/ftl/inspect_iterator.hpp
  tests/test_inspect_iterator.cpp
Labels: bug
